config/routes.rb
Rails.application.routes.draw do

  root 'tickets#new'
  devise_for :staffs, skip: [:registrations]

  resources :tickets, only: [:new, :create, :show, :update]
  resources :staff_members do
    get :edit_password, on: :member
    patch :update_password, on: :member
  end

  resources :staff_tickets, only: [:show] do
    get :unassigned, on: :collection
    get :on_hold, on: :collection
    get :opened, on: :collection
    get :closed, on: :collection
    patch :update_ticket, on: :member
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :staff
  belongs_to :ticket
end

app/models/department.rb
class Department < ActiveRecord::Base
  has_many :tickets
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :staffs

  validates :name, presence: true, uniqueness: true
end

app/models/staff.rb
class Staff < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :role_id, presence: true

  belongs_to :role
  has_many :tickets

  def to_label
    email
  end

  def admin?
    'admin' == Role.find(role_id).name
  end
end

app/models/status.rb
class Status < ActiveRecord::Base
  has_many :tickets

  validates :name, presence: true

  scope :ids_by_names, ->(names) {
    select(:id).where(name: names).pluck(:id)
  }
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  include HelpdeskUtils
  attr_accessor :capcha

  has_paper_trail on: [:update]

  has_many :comments, dependent: :destroy
  accepts_nested_attributes_for :comments,
                                reject_if: ->(obj) { obj[:body].blank? }

  belongs_to :department
  belongs_to :status
  belongs_to :staff

  before_create :generate_tickid
  before_create :set_status

  validates :name, :subject, :body, :department, presence: true
  validates :email, email_format: {
    message: "doesn't look like an email address"
  }
  validate  :check_for_spam_bot

  scope :unassigned, -> { where(staff: nil) }
  scope :assigned, -> { where.not(staff: nil) }
  scope :on_hold, -> {
    where(status_id: Status.ids_by_names('On Hold')).assigned
  }
  scope :opened, -> {
    where.not(status_id: Status.ids_by_names(['On Hold', 'Cancelled', 'Completed'])).assigned
  }
  scope :closed, -> {
    where(status_id: Status.ids_by_names(['Cancelled', 'Completed'])).assigned
  }

  def all_versions
    versions.map do |version|
      {
        event: version.event,
        author: Staff.find_by_id(version.whodunnit).try(:email) || 'customer',
        name: version.reify.name,
        status: version.reify.status.name,
        email: version.reify.email,
        department: version.reify.department.name,
        subject: version.reify.subject,
        body: version.reify.body,
        date: version.created_at
      } unless version.object.nil?
    end.compact
  end

  private

  def generate_tickid
    self.tickid = loop do
      gen_tickid = generate_random_ticket_token
      break gen_tickid unless Ticket.exists?(tickid: gen_tickid)
    end
  end

  def set_status
    self.status_id = self.status_id || 1
  end

  def check_for_spam_bot
    errors.add(:capcha, 'Spam protection') if capcha.present?
  end
end

app/models/ticket_observer.rb
class TicketObserver < ActiveRecord::Observer
  def after_create(ticket)
    p ticket
    TicketMailer.notify_customer(ticket).deliver
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception

  before_action :authenticate_staff!

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def current_user
    current_staff
  end

  protected

  def after_sign_in_path_for(resource)
    unassigned_staff_tickets_path
  end

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end

  private

  def user_not_authorized
    flash[:alert] = 'You are not authorized to perform this action'
    redirect_to(request.referrer || unassigned_staff_tickets_path)
  end
end

app/controllers/staff_members_controller.rb
class StaffMembersController < ApplicationController
  before_action :get_staff, only: [:update, :destroy, :edit_password, :update_password]
  def index
    @staff_new = Staff.new
    @staffs = Staff.all
    authorize @staffs
  end

  def create
    @staff = Staff.create(staff_params)
    authorize @staff
    if @staff.save
      redirect_to staff_members_path
    else
      redirect_to staff_members_path, alert: 'Error creating staff member'
    end
  end

  def update
    authorize @staff
    if @staff.update(staff_params)
      redirect_to staff_members_path
    else
      redirect_to staff_members_path, alert: 'Error editing staff member'
    end
  end

  def edit_password
    authorize @staff
  end

  def update_password
    authorize @staff
    if @staff.update(staff_params)
      sign_in @staff, bypass: true
      redirect_to root_path, notice: 'Password has been changed successfully'
    else
      render 'edit_password'
    end
  end

  def destroy
    authorize @staff
    staff = @staff.destroy
    redirect_to staff_members_path, notice: "#{staff.email} deteted successfully."
  end

  private
  def staff_params
    params.require(:staff).permit(:email, :password, :password_confirmation, :role_id)
  end

  def get_staff
    @staff = Staff.find_by_id(params[:id])
  end
end

app/controllers/staff_tickets_controller.rb
class StaffTicketsController < ApplicationController
  before_action :get_ticket, only: [:show, :update_ticket]

  def unassigned
    @tickets = Ticket.unassigned
  end

  def on_hold
    @tickets = Ticket.on_hold
  end

  def opened
    @tickets = Ticket.opened
  end

  def closed
    @tickets = Ticket.closed
  end

  def show
    @ticket.comments.build
    @current_staff_id = current_staff.id
  end

  def update_ticket
    @ticket.update(ticket_params)
    redirect_to staff_ticket_path(@ticket.tickid),
                notice: 'Successfull updated ticket'
  end

  private

  def get_ticket
    @ticket = Ticket.find_by_tickid(params[:id])
  end

  def ticket_params
    params.require(:ticket).permit(:department_id,
                                   :staff_id,
                                   :status_id,
                                   comments_attributes: [:body, :staff_id])
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  skip_action_callback :authenticate_staff!

  before_action :get_ticket, only: [:show, :update]

  def new
    @ticket = Ticket.new
    @departments = Department.all.map { |dep| [dep.name, dep.id] }
  end

  def create
    @ticket = Ticket.new(ticket_params)
    if @ticket.save
      redirect_to ticket_path(@ticket.tickid), notice: 'Ticket was created successfully.'
    else
      render :new
    end
  end

  def show
  end

  def update
    p @ticket
    if @ticket.update(ticket_params)
      redirect_to ticket_path(@ticket.tickid), notice: 'Ticket updated successfully'
    else
      render :show
    end
  end

  private
  def ticket_params
    params.require(:ticket).permit(:name,
                                   :email,
                                   :subject,
                                   :body,
                                   :department_id,
                                   :capcha,
                                   :status_id)
  end

  def get_ticket
    @ticket = Ticket.find_by_tickid(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navigation.html.haml
- if staff_signed_in?
  %nav.top-bar{"data-topbar" => "", :role => "navigation"}
    %ul.title-area
      %li.name
        %h1= link_to 'Helpdesk', root_url
    %section.top-bar-section
      %ul.left
        %li= link_to 'New Unassigned Tickets', unassigned_staff_tickets_path
        %li= link_to 'Open Tickets', opened_staff_tickets_path
        %li= link_to 'On hold tickets', on_hold_staff_tickets_path
        %li= link_to 'Closed Tickets', closed_staff_tickets_path
        %li= link_to 'Change Password', edit_password_staff_member_path(current_staff)
        %li= link_to 'Manage Members', staff_members_path if current_staff.admin?
      %ul.right
        %li.divider
        %li= link_to 'Log Out', destroy_staff_session_path, method: :delete
- else
  %nav.top-bar{"data-topbar" => "", :role => "navigation"}
    %ul.title-area
      %li.name
        %h1= link_to 'Helpdesk', root_url
    %section.top-bar-section
      %ul.right
        %li.divider
        %li= link_to 'Log In as Saff', new_staff_session_path

app/views/layouts/application.html.haml
!!!
%html{lang: "en"}
  %head
    %meta{charset: "utf-8"}
    %meta{name: "viewport", content: "width=device-width, initial-scale=1.0"}

    %title= content_for?(:title) ? yield(:title) : 'Helpdesk'

    = stylesheet_link_tag "application", 'data-turbolinks-track' => true
    = javascript_include_tag "vendor/modernizr", 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    = render 'layouts/navigation'

    .row
      .large-12.large-centered.columns
        %p.notice= notice
        %p.alert= alert

    .row
      .large-12.large-centered.columns
        = yield

    = javascript_include_tag "application", 'data-turbolinks-track' => true

app/views/staff_members/_edit_member.html.haml
.row
  = simple_form_for staff, url: staff_member_path(staff) do |f|
    .large-3.column
      = staff.email
    .large-3.column
      = f.association :role, collection: Role.all, include_blank: false
    .large-3.column
      = f.button :submit, class: 'tiny'

  .large-3.column
    = link_to 'Delete', staff_member_path(staff), method: :delete, data: { confirm: "Are you sure delete this member?" }, class: 'button tiny'

app/views/staff_members/_new_member.html.haml
.row
  = simple_form_for @staff_new, url: staff_members_path do |f|
    .large-3.columns
      = f.input :email, as: :email
    .large-3.columns
      = f.association :role, collection: Role.all, include_blank: false, priority: 'member'
    .large-2.columns
      = f.input :password, as: :password, hint: "8 characters minimum"
    .large-2.columns
      = f.input :password_confirmation, label: 'Password confirm', as: :password
    .large-2.columns
      = f.button :submit, class: 'small'

app/views/staff_members/edit_password.html.haml
.row
  = simple_form_for current_staff, url: update_password_staff_member_path do |f|
    .large-3.columns
      = f.input :password, as: :password
      = f.input :password_confirmation, as: :password
      = f.button :submit

app/views/staff_members/index.html.haml
%h1 Staff Memebers management
= render "new_member"
- @staffs.each do |staff|
  = render 'edit_member', staff: staff

app/views/staff_tickets/_comments_list.html.haml
- comments.each do |comment|
  .row
    .large-6.columns
      - if comment.created_at
        %span.label.secondary.round= time_ago_in_words(comment.created_at, include_seconds: true)
      - if comment.staff
        %span.label.secondary.round= comment.staff.email
        %p= comment.body

app/views/staff_tickets/_form.html.haml
= simple_form_for @ticket, url: update_ticket_staff_ticket_path(@ticket.tickid) do |f|
  .row
    .large-4.columns
      = f.association :status, include_blank: false
    .large-4.columns
      = f.association :department, include_blank: false
    .large-4.columns
      = f.association :staff, label: 'Owner'
  = render 'comments_list', comments: @ticket.comments
  .row
    .large-6.columns
      = f.simple_fields_for :comments do |c|
        - if c.object.id.nil?
          = c.input :body
          = c.input :staff_id, as: :hidden, input_html: { value: @current_staff_id }
  = f.button :submit

app/views/staff_tickets/_list.html.haml
- tickets.each do |ticket|
  .row
    .large-12.columns
      %span.label.secondary.round= distance_of_time_in_words_to_now(ticket.created_at)
      %span.label.warning.round= ticket.department.name
      %span.label.success.round= ticket.status.name
      %h6= ticket.email
      %h3= link_to ticket.subject, staff_ticket_path(ticket.tickid)
      -if ticket.staff
        %p= "Owner #{ticket.staff.email}"
      %p= ticket.body
  %p

app/views/staff_tickets/closed.html.haml
%h1 Colsed Tickets
= render 'list', tickets: @tickets

app/views/staff_tickets/on_hold.html.haml
%h1 On Hold Tickets
= render 'list', tickets: @tickets

app/views/staff_tickets/opened.html.haml
%h1 Opened Tickets
= render 'list', tickets: @tickets

app/views/staff_tickets/show.html.haml
%span.label.secondary.radius= @ticket.tickid
%span.label.secondary.radius= distance_of_time_in_words_to_now @ticket.created_at

%h2= @ticket.subject
%p= @ticket.body

= render 'form'
= render 'tickets/history', ticket_object: @ticket

app/views/staff_tickets/unassigned.html.haml
%h1 Unassigned Tickets
= render 'list', tickets: @tickets

app/views/tickets/_form.html.haml
.row
  .large-4.columns
    = f.input :name
  .large-4.columns
    = f.input :email, as: :email
  .large-4.columns
    = f.association :department, collection: Department.all, include_blank: false
.row
  .large-8.columns
    = f.input :subject
.row
  .large-12.columns
    = f.input :body, as: :text
    = f.button :submit
#capcha
  = f.input :capcha, label: 'Don\'t fill this field, please', style: 'display: none;'

app/views/tickets/_history.html.haml
%h3 History Log
- ticket_object.all_versions.each do |ticket|
  .row
    .large-4.columns
      %span.label.success.round= ticket[:event]
      %span.label.round= distance_of_time_in_words_to_now(ticket[:date], include_seconds: true)
      %span.label.secondary.round= "by #{ticket[:author]}"
    .large-8.columns
      .row
        %span.label.warning.round Status
        = ticket[:status]
      .row
        %span.label.warning.round Name
        = ticket[:name]
      .row
        %span.label.warning.round Email
        = ticket[:email]
      .row
        %span.label.warning.round Department
        = ticket[:department]
      .row
        %span.label.warning.round Subject
        = ticket[:subject]
      .row
        %span.label.warning.round Body
        = ticket[:body]
  %p

app/views/tickets/new.html.haml
%h2 Create new ticket
%p Please, fill all fields.
= simple_form_for @ticket do |f|
  = render 'form', f: f

app/views/tickets/show.html.haml
%h2 Your ticket ##{@ticket.tickid}
%p= "Status: #{@ticket.status.name}"
= simple_form_for @ticket, url: ticket_path(@ticket.tickid) do |f|
  = render 'form', f: f
= render 'history', ticket_object: @ticket